- name: Change GRUB configuration
  hosts: all
  become: yes

  tasks:
    - name: Change grub config
      lineinfile:
        state: present
        dest: /etc/default/grub
        backrefs: yes
        regexp: "^(GRUB_CMDLINE_LINUX=(?!.* {{ item }})\"[^\"]+)(\".*)"
        line: '\1 {{ item }}\2'
      loop:
        - net.ifnames=0
        - biosdevname=0
      notify: Write changes

  handlers:
    - name: Write changes
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
