---
- name: Remove Apache index.html
  hosts: all
  become: yes

  vars:
    f: /var/www/html/index.html

  tasks:
  - name: Remove Apache
    yum: name=httpd state=absent

  - name: Remove index.html
    file: path={{ f }} state=absent

  - name: Close http port
    firewalld: service=http permanent=true state=disabled
    notify: Restart Firewalld



  handlers:
  - name: Restart Firewalld
    service: name=firewalld state=restarted
